
import "./globals.css";
import Navbar from "./head/Nav";
import Foter from "./head/Footer";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import "bootstrap/dist/css/bootstrap.min.css";
import Foo from "./head/Foo";


export const metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Navbar/>

<div className=" my-4  border-2 border-green-500  mx-5 rounded-md">

<marquee>

  <h1>
    thi is me th syir wb site rith now thodign
  </h1>
</marquee>


</div>
        {children}
        
        

<Foo/>
        <ToastContainer/>
        </body>
    </html>
  );
}
